# Generated by Django 5.2 on 2025-09-27 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('landreg', '0003_add_cadster_newfilds'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPelakPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pelak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landreg.pelak', verbose_name='پلاک')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'دسترسی کاربر به پلاک',
                'verbose_name_plural': 'دسترسی\u200cهای کاربران به پلاک\u200cها',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='pelaks',
            field=models.ManyToManyField(blank=True, help_text='پلاک\u200cهایی که این کاربر به آن\u200cها دسترسی دارد', related_name='authorized_users', through='accounts.UserPelakPermission', to='landreg.pelak', verbose_name='پلاک\u200cهای مجاز'),
        ),
        migrations.AddIndex(
            model_name='userpelakpermission',
            index=models.Index(fields=['user', 'pelak'], name='accounts_us_user_id_5a1d57_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userpelakpermission',
            unique_together={('user', 'pelak')},
        ),
    ]
