# Generated by Django 5.2 on 2025-09-21 11:19

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fa', models.CharField(unique=True, verbose_name='نام')),
                ('cnter_name_fa', models.CharField(unique=True, verbose_name='نام مرکز')),
                ('code', models.PositiveIntegerField(unique=True, verbose_name='کد')),
                ('border', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name': 'استان',
                'verbose_name_plural': 'استان ها',
            },
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fa', models.CharField(unique=True, verbose_name='نام')),
                ('code', models.PositiveIntegerField(unique=True, verbose_name='کد')),
                ('border', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rprovince', to='common.province')),
            ],
            options={
                'verbose_name': 'شهرستان',
                'verbose_name_plural': 'شهرستان ها',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('name', models.CharField(max_length=100, verbose_name='نام شرکت')),
                ('typ', models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع شرکت')),
                ('callnumber', models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره تماس')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='آدرس')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='توضیحات')),
                ('is_nazer', models.BooleanField(default=False, verbose_name='ناظر استانی است؟')),
                ('is_supernazer', models.BooleanField(default=False, verbose_name='ناظر عالی است؟')),
                ('is_moshaver', models.BooleanField(default=False, verbose_name='مشاور است؟')),
                ('provinces', models.ManyToManyField(blank=True, related_name='companies', to='common.province', verbose_name='استان\u200cها')),
            ],
            options={
                'verbose_name': 'لیست شرکت',
                'verbose_name_plural': 'لیست شرکت ها',
            },
        ),
    ]
