# Generated by Django 5.2 on 2025-09-29 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='typ',
        ),
    ]
