# Generated by Django 5.2 on 2025-09-24 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('landreg', '0001_init_langreg'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OldCadasterData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('table_name', models.CharField(db_index=True, help_text='نام جدول مربوطه در دیتابیس', max_length=100, verbose_name='نام جدول در دیتابیس')),
                ('status', models.CharField(choices=[('1', 'مچ نشده'), ('2', 'مچ شده')], db_index=True, default='1', max_length=1, verbose_name='وضعیت')),
                ('matched_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاریخ مچ شدن')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_old_cadaster_data', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
                ('matched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_old_cadaster_data', to=settings.AUTH_USER_MODEL, verbose_name='مچ شده توسط')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_cadaster_data', to='common.province', verbose_name='استان مربوطه')),
            ],
            options={
                'verbose_name': 'داده کادستر قدیمی',
                'verbose_name_plural': 'داده\u200cهای کادستر قدیمی',
                'indexes': [models.Index(fields=['status', 'province'], name='landreg_old_status_8da66b_idx'), models.Index(fields=['matched_at', 'status'], name='landreg_old_matched_b092c9_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('matched_at__isnull', True), ('matched_by__isnull', True)), models.Q(('matched_at__isnull', False), ('matched_by__isnull', False)), _connector='OR'), name='matched_fields_consistency')],
            },
        ),
    ]
