# Generated by Django 5.2 on 2025-09-27 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landreg', '0002_add_table_oldcadaster'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cadaster',
            name='change_status_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ruser_changestatusby', to=settings.AUTH_USER_MODEL, verbose_name='تغییر وضعیت داده شده توسط'),
        ),
        migrations.AddField(
            model_name='cadaster',
            name='change_status_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تایید نظارت'),
        ),
    ]
