# Generated by Django 5.2 on 2025-09-29 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landreg', '0003_add_cadster_newfilds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadaster',
            name='nezarat_type',
            field=models.CharField(blank=True, choices=[('سازمان نقشه برداری', 'سازمان نقشه برداری'), ('شمیم', 'شمیم'), ('ارتوی دارای تایید', 'ارتوی دارای تایید')], max_length=50, null=True, verbose_name='نوع نظارت'),
        ),
        migrations.AlterField(
            model_name='cadaster',
            name='project_name',
            field=models.CharField(blank=True, choices=[('امور اراضی', 'امور اراضی'), ('دریاچه', 'دریاچه'), ('رودخانه مرزی', 'رودخانه مرزی')], max_length=50, null=True, verbose_name='نام پروژه'),
        ),
    ]
