# Generated by Django 5.2 on 2025-09-29 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landreg', '0004_Chng_nezarattype_projectname_nullable'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cadaster',
            name='landreg_cad_pelak_i_7d4ce9_idx',
        ),
        migrations.RemoveField(
            model_name='cadaster',
            name='pelak',
        ),
    ]
