# Generated by Django 5.2 on 2025-09-30 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landreg', '0005_remove_plak_cadaster_rel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadaster',
            name='status',
            field=models.IntegerField(choices=[(0, 'پیش فرض'), (1, 'قطعات بدون تغییر در محدوده'), (2, ' مرز قطعات دارای تغییر جزئی در محدوده'), (3, 'قطعات تفکیک شده'), (4, 'قطعات کاملاً غیر همخوان')], default=5, verbose_name='وضعیت'),
        ),
    ]
