# Generated by Django 5.2 on 2025-10-01 06:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landreg', '0006_chng_cadaster_status_nums'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cadaster',
            index=models.Index(fields=['status'], name='landreg_cad_status_6a841e_idx'),
        ),
    ]
