# Generated by Django 5.2 on 2025-10-01 08:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landreg', '0007_add_special_indexs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadaster',
            name='irrigation_type',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='نام آبیاری'),
        ),
        migrations.AlterField(
            model_name='cadaster',
            name='land_use',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع کاربری'),
        ),
        migrations.AlterField(
            model_name='cadaster',
            name='change_status_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ruser_changestatusby', to=settings.AUTH_USER_MODEL, verbose_name='تغییر وضعیت داده شده در تاریخ'),
        ),
        migrations.AlterField(
            model_name='cadaster',
            name='change_status_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تغییر وضعیت'),
        ),
        migrations.AlterField(
            model_name='cadaster',
            name='jaam_code',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(code='invalid_jaam_code', message='این فیلد فقط می\u200cتواند شامل اعداد باشد (0-9)', regex='^\\d+$')], verbose_name='کد جام'),
        ),
        migrations.AlterField(
            model_name='cadaster',
            name='nezarat_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع نظارت'),
        ),
        migrations.AlterField(
            model_name='cadaster',
            name='nezart_verify_date',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='تاریخ تایید نظارت'),
        ),
        migrations.AlterField(
            model_name='cadaster',
            name='ownership_kinde',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='نوع مالکیت'),
        ),
        migrations.AlterField(
            model_name='cadaster',
            name='project_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نام پروژه'),
        ),
        migrations.AlterField(
            model_name='cadaster',
            name='uniquecode',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='کد یکتا'),
        ),
        migrations.DeleteModel(
            name='IrrigationTypDomain',
        ),
        migrations.DeleteModel(
            name='LandUseDomain',
        ),
    ]
