# Generated by Django 5.2 on 2025-10-01 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landreg', '0008_chng_cadaster_domin_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='flag',
            name='change_status_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تغییر وضعیت داده شده در'),
        ),
        migrations.AlterField(
            model_name='flag',
            name='createdby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_flags', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط'),
        ),
    ]
